/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    SearchBar: typeof import('./components/SearchBar.vue')['default']
    SuggertionsList: typeof import('./components/SuggertionsList.vue')['default']
  }
}
